global:
  scrape_interval: 1s # makes for a good demo

scrape_configs:
  - job_name: 'resource-server'
    static_configs:
      - targets: ['host.docker.internal:5002'] # hard-coded port matches launchSettings.json
