//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PocketStorage.Client.Shared.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_cs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_cs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PocketStorage.Client.Shared.ResourceFiles.Resource.cs", typeof(Resource_cs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pocket Storage.
        /// </summary>
        internal static string Common_AppName {
            get {
                return ResourceManager.GetString("Common_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlásit se.
        /// </summary>
        internal static string Layout_Authenticator_SignInButton {
            get {
                return ResourceManager.GetString("Layout_Authenticator_SignInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odhlásit se.
        /// </summary>
        internal static string Layout_Authenticator_SignOutButton {
            get {
                return ResourceManager.GetString("Layout_Authenticator_SignOutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Účet.
        /// </summary>
        internal static string Layout_Avatar_AccountButton {
            get {
                return ResourceManager.GetString("Layout_Avatar_AccountButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claims.
        /// </summary>
        internal static string Layout_MainLayout_ClaimsButton {
            get {
                return ResourceManager.GetString("Layout_MainLayout_ClaimsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domů.
        /// </summary>
        internal static string Layout_MainLayout_HomeButton {
            get {
                return ResourceManager.GetString("Layout_MainLayout_HomeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soukromí.
        /// </summary>
        internal static string Layout_MainLayout_PrivacyButton {
            get {
                return ResourceManager.GetString("Layout_MainLayout_PrivacyButton", resourceCulture);
            }
        }
    }
}
